<?php

// This file was generated by liblab | https://liblab.com/

namespace Celitech\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetEsimOkResponse
{
    #[SerializedName('esim')]
    public ?GetEsimOkResponseEsim $esim;

    public function __construct(?GetEsimOkResponseEsim $esim = null)
    {
        $this->esim = $esim;
    }
}
