<?php

// This file was generated by liblab | https://liblab.com/

namespace Celitech\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum GrantType: string
{
    case ClientCredentials = 'client_credentials';
}
