<?php

// This file was generated by liblab | https://liblab.com/

namespace Celitech\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class TopUpEsimOkResponseProfile
{
    /**
     * ID of the eSIM
     */
    #[SerializedName('iccid')]
    public ?string $iccid;

    public function __construct(?string $iccid = null)
    {
        $this->iccid = $iccid;
    }
}
